#!/usr/bin/env node
// Builds the comparison chart's HTML *from readme.md's own tables*.
//
// Why: the chart and the tables drifted the moment a status changed, and a wrong
// picture above the fold is worse than no picture. Generating the image from the
// tables makes that class of bug structurally impossible — if they disagree, this
// script is the thing that's broken, not the data.
//
//   node scripts/build-chart.mjs > /tmp/chart.html
//   node ~/.claude/skills/mph-figure/scripts/render.mjs --in /tmp/chart.html --html \
//     --out images/broker-mcp-full-comparison.png --width 1180 --scale 2

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const md = readFileSync(join(ROOT, "readme.md"), "utf8");

const esc = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// Strip markdown inline syntax down to display text, keeping link labels.
function plain(s) {
  return s
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\*\*/g, "") // bold only — a lone * is load-bearing here ("E*TRADE", "Yes*")
    .replace(/`/g, "")
    .replace(/⚠️\s*/g, "")
    .trim();
}

// Walk readme.md, collecting tables under their nearest ## / ### heading.
function collect() {
  const lines = md.split("\n");
  const out = [];
  let h2 = "";
  let h3 = "";
  let cur = null;

  for (const line of lines) {
    const m2 = line.match(/^## (.+)/);
    const m3 = line.match(/^### (.+)/);
    if (m2) {
      h2 = m2[1].trim();
      h3 = "";
      cur = null;
      continue;
    }
    if (m3) {
      h3 = m3[1].trim();
      cur = null;
      continue;
    }
    if (/^\|/.test(line)) {
      if (/^\|\s*-+/.test(line.replace(/\s/g, "").replace(/\|/g, "|"))) continue;
      if (/^\|[\s|:-]+\|$/.test(line)) continue;
      const cells = line.split("|").slice(1, -1).map((c) => c.trim());
      if (!cells.length) continue;
      // header row of each table
      if (/^(Broker|Exchange|Aggregator)$/i.test(cells[0])) {
        cur = { h2, h3, rows: [] };
        out.push(cur);
        continue;
      }
      if (cur) cur.rows.push(cells);
    }
  }
  return out.filter((t) => t.rows.length);
}

// Map a "Trades?" cell to a pill.
function pill(raw) {
  const t = plain(raw).toLowerCase();
  if (t.startsWith("draft")) return ["DRAFT-ONLY", "draft"];
  if (t === "none") return ["NONE", "none"];
  if (t === "no" || t.startsWith("no ")) return ["READ-ONLY", "read"];
  if (t.startsWith("both")) return ["BOTH", "both"];
  if (t.startsWith("varies")) return ["VARIES", "warn"];
  if (t.startsWith("see page")) return ["SEE PAGE", "warn"];
  if (t.startsWith("code says")) return ["DEAD UPSTREAM", "dead"];
  if (t.startsWith("yes")) return ["FULL", "full"];
  return [plain(raw).toUpperCase() || "—", "warn"];
}

const groups = collect();

let body = "";
for (const g of groups) {
  const title = g.h3 ? `${g.h2} — ${g.h3}` : g.h2;
  body += `<div class="sec">${esc(title.toUpperCase())}</div>\n<table>`;
  for (const r of g.rows) {
    const isNeg = /Confirmed no MCP route/i.test(g.h2);
    if (isNeg) {
      body += `<tr><td class="nm">${esc(plain(r[0]))}</td><td class="pl"><span class="p none">NONE</span></td><td class="ty">—</td><td class="cv">${esc(plain(r[1] || ""))}</td></tr>`;
      continue;
    }
    // Aggregators:  | Aggregator | Trades? | Covers |
    if (/^Aggregators$/i.test(g.h2)) {
      const [label, cls] = pill(r[1]);
      body += `<tr><td class="nm">${esc(plain(r[0]))}</td><td class="pl"><span class="p ${cls}">${esc(label)}</span></td><td class="ty">—</td><td class="cv">${esc(plain(r[2] || ""))}</td></tr>`;
      continue;
    }
    // Reachable-only: | Broker | Route | Trading |  — the pill comes from Trading (col 2),
    // and Route is the note. Reading col 1 here put "SnapTrade / Truthifi" in the pill.
    if (/Reachable only/i.test(g.h2)) {
      const [label, cls] = pill(r[2]);
      body += `<tr><td class="nm">${esc(plain(r[0]))}</td><td class="pl"><span class="p ${cls}">${esc(label)}</span></td><td class="ty">${esc(plain(r[1] || ""))}</td><td class="cv">No direct server — aggregator route only</td></tr>`;
      continue;
    }
    const [label, cls] = pill(r[1]);
    body += `<tr><td class="nm">${esc(plain(r[0]))}</td><td class="pl"><span class="p ${cls}">${esc(label)}</span></td><td class="ty">${esc(plain(r[3] || ""))}</td><td class="cv">${esc(plain(r[2] || ""))}</td></tr>`;
  }
  body += `</table>\n`;
}

const total = groups.reduce((n, g) => n + g.rows.length, 0);

process.stdout.write(`<!-- generated by scripts/build-chart.mjs from readme.md -->
<style>
  :root { color-scheme: dark; }
  body { margin:0; background:#0b0d12; color:#e8eaf0;
         font-family: -apple-system, "Segoe UI", Inter, Helvetica, Arial, sans-serif; }
  .wrap { padding: 34px 30px 26px; }
  .kicker { color:#f0a63a; font-size:11px; letter-spacing:.19em; font-weight:700; }
  h1 { font-size:31px; margin:9px 0 5px; letter-spacing:-.4px; font-weight:700; }
  .sub { color:#8b93a6; font-size:12.5px; margin-bottom:16px; }
  .legend { display:flex; gap:17px; flex-wrap:wrap; margin:0 0 20px; font-size:10.5px; color:#8b93a6; }
  .dot { width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:5px;vertical-align:1px; }
  .sec { color:#f0a63a; font-size:10px; letter-spacing:.15em; font-weight:700;
         margin:19px 0 6px; padding-top:11px; border-top:1px solid #1e232e; }
  table { width:100%; border-collapse:collapse; }
  tr { border-bottom:1px solid #151922; }
  td { padding:7px 9px 7px 0; vertical-align:middle; font-size:12px; }
  .nm { width:158px; font-weight:600; color:#fff; }
  .pl { width:104px; }
  .ty { width:132px; font-family:ui-monospace,"SF Mono",Menlo,monospace;
        font-size:10.5px; color:#7d879c; }
  .cv { color:#aab2c4; line-height:1.45; }
  .p { display:inline-block; padding:2.5px 7px; border-radius:4px;
       font-size:9px; font-weight:800; letter-spacing:.06em; white-space:nowrap; }
  .full  { background:#123527; color:#3ddc97; }
  .draft { background:#3a2d10; color:#f0a63a; }
  .both  { background:#2a2340; color:#a78bfa; }
  .read  { background:#20242e; color:#98a2b8; }
  .warn  { background:#3a2d10; color:#f0a63a; }
  .dead  { background:#3a1520; color:#f46b7f; }
  .none  { background:#3a1520; color:#f46b7f; }
  .foot { margin-top:22px; padding:13px 15px; border:1px solid #2a2f3d;
          border-left:3px solid #f0a63a; border-radius:5px;
          background:#11141b; font-size:11.5px; color:#aab2c4; line-height:1.55; }
  .foot b { color:#f0a63a; }
</style>
<div class="wrap">
  <div class="kicker">AWESOME BROKER MCP</div>
  <h1>Which brokers can an AI actually trade through?</h1>
  <div class="sub">${total} entries · every claim checked at a first-party source · generated from the README tables, so it cannot contradict them</div>
  <div class="legend">
    <span><span class="dot" style="background:#3ddc97"></span>Full trading</span>
    <span><span class="dot" style="background:#f0a63a"></span>Draft-only / gated</span>
    <span><span class="dot" style="background:#98a2b8"></span>Read-only</span>
    <span><span class="dot" style="background:#f46b7f"></span>No MCP route</span>
  </div>
  ${body}
  <div class="foot">
    <b>The pattern worth noticing:</b> official integrations trend conservative — hosted plus
    draft-approval (IBKR, Trade It), or hosted with genuinely no execution path (SnapTrade,
    Truthifi, Webull Cloud). The brokers with the most compliance exposure chose the most
    cautious posture. Community servers mostly skip straight to direct execution with no
    platform-level approval step; there the guardrail is whatever <i>you</i> configure
    client-side, not something the broker enforces. And crypto is years ahead of traditional
    brokerage on shipping first-party servers at all.
  </div>
</div>
`);
